-- Side-by-side schema for abr-backend/NestJS.
-- Safe goal: create the new TypeORM tables without deleting or renaming
-- existing Prisma tables such as "User", "Product", "Sale", etc.

create extension if not exists pgcrypto;

do $$ begin
  create type users_role_enum as enum ('SUPERADMIN', 'ADMIN', 'WORKER');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type products_unit_enum as enum ('PIECE', 'KILOGRAM');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type cash_register_sessions_status_enum as enum ('OPEN', 'CLOSED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type cash_movements_type_enum as enum ('SUPPLIER_PAYMENT', 'WITHDRAWAL', 'EXPENSE', 'CASH_IN', 'ADJUSTMENT');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type sales_paymentmethod_enum as enum ('CASH', 'CARD', 'TRANSFER', 'CREDIT');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type sale_items_unit_enum as enum ('PIECE', 'KILOGRAM');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type held_tickets_paymentmethod_enum as enum ('CASH', 'CARD', 'TRANSFER', 'CREDIT');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type held_ticket_items_unit_enum as enum ('PIECE', 'KILOGRAM');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type stock_exits_reason_enum as enum ('EXPIRED', 'DAMAGED');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type stock_exits_unit_enum as enum ('PIECE', 'KILOGRAM');
exception when duplicate_object then null;
end $$;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  "fullName" varchar not null,
  email varchar not null unique,
  username varchar unique,
  "passwordHash" varchar not null,
  phone varchar not null,
  role users_role_enum not null default 'WORKER',
  active boolean not null default true
);

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  sku varchar not null unique,
  name varchar not null,
  description varchar,
  "costPrice" numeric(10, 2) not null default 0,
  "profitMargin" numeric(7, 2) not null default 0,
  price numeric(10, 2) not null,
  unit products_unit_enum not null default 'PIECE',
  stock numeric(12, 3) not null default 0,
  active boolean not null default true,
  "createdAt" timestamp not null default now(),
  "updatedAt" timestamp not null default now()
);

create index if not exists "IDX_products_name" on products (name);
create index if not exists "IDX_products_active_updatedAt" on products (active, "updatedAt");
create index if not exists "IDX_products_active_stock" on products (active, stock);

create table if not exists cash_register_sessions (
  id uuid primary key default gen_random_uuid(),
  status cash_register_sessions_status_enum not null default 'OPEN',
  "openingAmount" numeric(12, 2) not null,
  "closingAmount" numeric(12, 2),
  "expectedAmount" numeric(12, 2),
  difference numeric(12, 2),
  "openedById" uuid not null references users(id),
  "closedById" uuid references users(id),
  notes varchar,
  "openedAt" timestamp not null default now(),
  "closedAt" timestamp
);

create index if not exists "IDX_cash_register_sessions_status_openedAt" on cash_register_sessions (status, "openedAt");

create table if not exists cash_movements (
  id uuid primary key default gen_random_uuid(),
  "cashSessionId" uuid not null references cash_register_sessions(id) on delete cascade,
  "createdById" uuid not null references users(id),
  type cash_movements_type_enum not null,
  amount numeric(12, 2) not null,
  description varchar not null,
  "createdAt" timestamp not null default now()
);

create index if not exists "IDX_cash_movements_cashSessionId_createdAt" on cash_movements ("cashSessionId", "createdAt");

create table if not exists sales (
  id uuid primary key default gen_random_uuid(),
  folio integer generated by default as identity unique,
  total numeric(12, 2) not null,
  "paymentTotal" numeric(12, 2),
  "itemCount" numeric(12, 3) not null,
  "paymentMethod" sales_paymentmethod_enum not null default 'CASH',
  "cashReceived" numeric(12, 2),
  "changeDue" numeric(12, 2),
  "sellerId" uuid not null references users(id),
  "cashSessionId" uuid references cash_register_sessions(id),
  "canceledAt" timestamp,
  "canceledById" uuid references users(id),
  "cancelReason" varchar,
  "creditPaidAt" timestamp,
  "creditPaidById" uuid references users(id),
  "creditPaymentMethod" sales_paymentmethod_enum,
  "creditCustomerName" varchar,
  "creditNote" varchar,
  "createdAt" timestamp not null default now()
);

create index if not exists "IDX_sales_createdAt" on sales ("createdAt");
create index if not exists "IDX_sales_paymentMethod_createdAt" on sales ("paymentMethod", "createdAt");

create table if not exists sale_items (
  id uuid primary key default gen_random_uuid(),
  "saleId" uuid not null references sales(id) on delete cascade,
  "productId" uuid references products(id) on delete set null,
  sku varchar not null,
  name varchar not null,
  description varchar,
  unit sale_items_unit_enum not null,
  quantity numeric(12, 3) not null,
  "unitPrice" numeric(10, 2) not null,
  "lineTotal" numeric(12, 2) not null,
  "canceledAt" timestamp,
  "cancelReason" varchar
);

create index if not exists "IDX_sale_items_saleId" on sale_items ("saleId");

create table if not exists held_tickets (
  id uuid primary key default gen_random_uuid(),
  note varchar,
  "itemCount" numeric(12, 3) not null,
  total numeric(12, 2) not null,
  "paymentMethod" held_tickets_paymentmethod_enum not null default 'CASH',
  "cashSessionId" uuid not null references cash_register_sessions(id) on delete cascade,
  "createdById" uuid not null references users(id),
  "createdAt" timestamp not null default now(),
  "updatedAt" timestamp not null default now()
);

create table if not exists held_ticket_items (
  id uuid primary key default gen_random_uuid(),
  "heldTicketId" uuid not null references held_tickets(id) on delete cascade,
  "productId" uuid references products(id) on delete set null,
  sku varchar not null,
  name varchar not null,
  description varchar,
  unit held_ticket_items_unit_enum not null,
  quantity numeric(12, 3) not null,
  "unitPrice" numeric(10, 2) not null,
  "lineTotal" numeric(12, 2) not null
);

create table if not exists stock_exits (
  id uuid primary key default gen_random_uuid(),
  "productId" uuid,
  "userId" uuid not null references users(id),
  reason stock_exits_reason_enum not null,
  sku varchar not null,
  name varchar not null,
  description varchar,
  unit stock_exits_unit_enum not null,
  quantity numeric(12, 3) not null,
  note varchar,
  "createdAt" timestamp not null default now()
);

